# If a value is set to a dictionary with a key named env the variable is replaced
# at runtime with the value specified in that environment variable. If the variable
# also has an optional attribute set then it will be set as None if no environment
# variable is set.

[python]
# Sets the root log level.
log_level = "INFO"

# Sets the logging level used for discord.py, DEBUG is not recommended even in local setups.
discord_log_level = "INFO"

[bot]
# The prefixes Metricity respond to.
command_prefix = ["m!"]

# The token Metricity will use to authenticate with Discord.
token = { env = "BOT_TOKEN" }

# The guild ID that Metricity should be reporting about
guild_id = 267624335836053506

# This is the role ID of the role that should identify staff members, for Fabricord this is the staff ID
staff_role_id = 765938438989152266

# Channels that should be flagged as staff only by category ID
staff_categories = [
    705216231010992178,
]

# Don't report messages for the following categories
ignore_categories = [
    764817953463861288
]

# Respond to opt-in/opt-out commands in the following channel
bot_commands_channel = 523633816078647296

# Role ID that is used as a role gate on the server
role_gate_id = 0  # We don't currently have one

[database]
# Postgres!

# If a database URI is passed in the "uri" variable it will override any specifics passed

uri = { env = "DATABASE_URI", optional = true }

# Otherwise, the below configuration options should be specified

host = "127.0.0.1"
port = 5432
database = "metricity"
username = "postgres"
password = "postgres"
